### ISSUE TITLE
Issue with CPT

### ISSUE THREAD

**Issue by fabien-corail** [addisonhall/generatepress-child#1]
Hey Addison,

It seems the way you handle CPT is not working properly anymore.

Fabien

**Comment by addisonhall** [comment]
Would you mind sharing the piece of code that's causing problems? Something like this should still work:

```php
add_filter( 'the_content', 'gpc_cpt_content' );
function gpc_cpt_content( $content ) {
    if ( is_singular( 'custom_post_type_name' ) && is_main_query() && in_the_loop() ) {
        include get_stylesheet_directory() . '/partials/content-cpt-sample-single.php';
    } elseif ( is_post_type_archive( 'custom_post_type_name' ) && is_main_query() ) {
        include get_stylesheet_directory() . '/partials/content-cpt-sample-archive.php';
    } else {
        return $content;
    }
}
```

But I'll take a look. Thanks.

**Comment by fabien-corail** [comment]
I've used this code ;-) But it duplicates the `article` : https://share.getcloudapp.com/wbu09BnD

**Comment by addisonhall** [comment]
Well, that's interesting... I'll create a test and see what happens on my end.

**Comment by addisonhall** [comment]
My test worked using this:

```php
add_filter( 'the_content', 'gpc_cpt_content' );
function gpc_cpt_content( $content ) {
    if ( is_singular( 'project' ) && is_main_query() && in_the_loop() ) {
        include get_stylesheet_directory() . '/partials/content-cpt-sample-single.php';
    } elseif ( is_post_type_archive( 'project' ) && is_main_query() ) {
        include get_stylesheet_directory() . '/partials/content-cpt-sample-archive.php';
    } else {
        return $content;
    }
}
```
But I may see the problem. Using `the_content` in GeneratePress will replace everything within `<div class="entry-content" itemprop="text"></div>`, so if your partial also uses the `<article id="post-###"...` markup, it will definitely repeat. Is that what's happening?

**Comment by fabien-corail** [comment]
Yes ! Good catch !

**Comment by addisonhall** [comment]
Hooray! I'm glad we got that figured out. And thanks for using this child theme -- I'm glad others are finding it useful.
