### ISSUE TITLE
Add login logo

### ISSUE THREAD

**Issue by danstramer** [addisonhall/generatepress-child#2]
Wasn't sure where to leave this comment, but on my projects I also add this code snippet which ads a logo to the login screen:

`/** Custom Log-in logo   **/
function my_custom_login_logo() {
    echo '<style type="text/css">
        h1 a { background-image:url('.get_bloginfo('stylesheet_directory').'/images/custom-login-logo.jpg) !important; background-size:auto !important; background-size:auto auto !important; width:310px !important; height:100px !important; }
    </style>';
}

add_action('login_head', 'my_custom_login_logo');
 `

**Comment by addisonhall** [comment]
Yes! I'm definitely adding something like this. I'm currently working on ditching jQuery... I'll get this added shortly after that. I appreciate the share.

**Comment by addisonhall** [comment]
Just added: https://github.com/addisonhall/generatepress-child/commit/e33e3de21f18854eb3ef88c6633aeffbd5da79cd

I set it up so that it pulls the site logo, if available. Thanks!
